import type { Metadata } from "next";
import "./globals.scss";
import LayoutClient from "./layout.client";
import { Inter, Permanent_Marker, Montserrat } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.variable}  ${montserrat.variable}`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
